### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by pavoltravnik** [tlsnotary/pagesigner-browserless#1]
When trying `python notarize.py ills.bandcamp.com/album/ornamental-or-mental` this will create file, which works fine in chrome, but when I try to make notarysation in cli `python auditor.py 1.pgsg` it returns:

```
Notary pubkey OK
Traceback (most recent call last):
  File "auditor.py", line 111, in <module>
    server_mod, server_exp = audit_session.extract_mod_and_exp(certDER=audit_data['certs'][3:3+first_cert_len], sn=True)
  File "/Users/name/GIT/pagesigner-browserless/src/shared/tlsn_ssl.py", line 732, in extract_mod_and_exp
    self.server_name = str(rv[0].getComponentByPosition(0).getComponentByPosition(5).getComponentByPosition(4).getComponentByPosition(0).getComponentByPosition(1))
  File "/Users/name/GIT/pagesigner-browserless/src/auditee/python/pyasn1-0.1.7/pyasn1/type/univ.py", line 765, in getComponentByPosition
    return self._componentValues[idx]
IndexError: list index out of range
```

**Comment by themighty1** [comment]
@pavoltravnik , sorry for taking this long to respond. Somehow your issue flew under the radar, Please try the updated version.
